apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  type: LoadBalancer
  ports:
  - 
    name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: test-api