apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api-deployment
  labels:
    app: test-api
    version: 1.0.0
    environment: development

spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-api
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
        - 
          name: test-api
          image: novan921/test-repo-api
          imagePullPolicy: Always
          ports:
            - containerPort: 3000