version: '3.4'

services:
  api:
    build:
      context: .
    # networks:
    #   - frontend
    #   - backend
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:3000
    restart: always
    container_name: test-app