version: '3.4'

services:
  api:
    build:
      context: .
    networks:
      - frontend
      - backend
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:3000
    restart: unless-stopped
    container_name: test-app

  mysql:
    image: mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=270598
    ports:
      - 3306:3306
    restart: unless-stopped
    container_name: test-mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    networks:
      - backend
    environment:
      - PMA_HOST=test-mysql
      - PMA_PORT=3306
    ports:
      - 8081:80
    restart: unless-stopped
    container_name: test-phpmyadmin

networks:
  frontend:
  backend: